# Generated by Django 3.2.4 on 2021-07-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
