# Generated by Django 3.2.4 on 2021-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='achievements',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
